apiVersion: v1
kind: Pod
metadata:
  namespace: roboshop
  name: mutli-container
spec:
  containers:
  - name: hello-pod-1
    image: nginx
    ports:
    - containerPort: 80
  - name: almalinux
    image: almalinux:8
    command: ["sleep", "300"]
  
